### PR TITLE
fix: use is-typed-array instead of which-typed-array

### PR DESCRIPTION
**Pull request by Uzlopak**
We should use is-typed-array instead of which-typed-array.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
thanks, good catch

**Comment by ljharb** [comment]
altho, there's really no point in doing this, since is-typed-array just calls which-typed-array.

**Comment by kibertoad** [comment]
@ljharb Clear benefit here would be 4 less dependencies, for no loss in compatibility or behaviour robustness. What is the disadvantage?

**Comment by kibertoad** [comment]
oh, sorry, I thought which-typed-array used is-typed-array, but it's the other way around, so yeah, that would be one extra dependency. my bad.

**Comment by ljharb** [comment]
I'd forgotten, but this is actually why I chose which-typed-array in the first place - because it does the same job with fewer dependencies.

**Comment by AaronDewes** [comment]
> I'd forgotten, but this is actually why I chose which-typed-array in the first place - because it does the same job with fewer dependencies.

Why did you even create `is-typed-array` if `which-typed-array` is sufficient?

**Comment by ljharb** [comment]
Initially it didn’t use which-typed-array, and, it’s clearer to have a predicate for the relevant use cases. Later i refactored to have one use the other, to maximize dependency deduplication.

**Pull request closed without merging**
